name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - "smarthub-library"  # Here source code branch is `master`, it could be other branch

jobs:
    jekyll:
      runs-on: windows
      steps:
      - uses: actions/checkout@v2
      # Standard usage
      - uses:  helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
